service: sqsapp

plugins: 
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage" 
        - "sqs:GetQueueUrl"
      Resource:   "arn:aws:sqs:${self:provider.region}:*:MyQueue"
  environment:
   ## MyQueue: !Ref MyQueue
   MyQueue: { Ref: MyQueue }

functions:
  sender:
    name: diegoTolaba-sender
    description: 'SQS Sender'
    handler: sender.handler
    events:
      - http:
          path: sls-sqs/sender
          method: post
  receiver:
    name: diegoTolaba-receiver
    description: 'SQS Receiver'
    handler: receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
