service: nx-diego-training

provider:
    name: aws
    region: us-east-1
    runtime: nodejs16.x

functions:
    HelloWorld:
        name: diegoTolaba-firstApp
        description: 'An API that resturns Hello World'
        handler: app.handler
        events:
          - http: 
              path: hello-world
              method: GET
